version: '3'
services:
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:16.2.3-ce.0'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.3.21:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        nginx['listen_port'] = 80
    ports:
      - '8900:80'
      - '8901:443'
      - '8902:22'
    volumes:
      - './data/gitlab/etc:/etc/gitlab'
      - './data/gitlab/log:/var/log/gitlab'
      - './data/gitlab/opt:/var/opt/gitlab'
